server:
  port: 8080

logging:
  level:
    org:
      springframwork:
        boot: INFO
    pl:
      futurecollars:
        invoicing: WARN
        invoicing.db: DEBUG


spring:
  profiles:
    active: memory
  flyway:
    enabled: false
  security:
    user:
      name: Szymon
      password: maslo

