spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/invoicing_mirror2
    username: postgres
    password: Parapet
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true

invoicng-system:
  database: sql