server:
  port: 8080

logging:
  level:
    org:
      springframwork:
        boot: INFO
    pl:
      futurecollars:
        invoicing: WARN
        invoicing.db: DEBUG

invoicing-system:
  database: sql

spring:
  profiles:
    active: sql
  flyway:
    enabled: false
