server:
  port: 8080

invoicing-system:
  database: file
  database.directory: db
  database.invoices.file: invoices.txt
  database.id.file: id.txt

logging:
  level:
    org:
      springframwork:
        boot: INFO
    pl:
      futurecollars:
        invoicing: WARN
        invoicing.db: DEBUG